name: nobet
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pandas=2.2.2
  - numpy=1.26.4
  - sqlalchemy=2.0.36
  - openpyxl=3.1.5
  - xlrd=1.2.0
  - reportlab=4.2.2
  - matplotlib=3.9.1
  - seaborn=0.13.2
  - tabulate=0.9.0
  - requests=2.32.3
  - tqdm=4.66.5
  - pyqt=5.15.10
  - pyqtwebengine=5.15.6
  - qtawesome=1.3.1
  - black=24.8.0
  - flake8=7.1.1
  - pytest=8.3.3
  - pip
  - pip:
      - pyqt5-tools==5.15.9.3.3
